os: osx
language: c
env:
  global:
    - PACKDIR=dist
#install:
#  - brew install postgresql@9.6
script:
#  - env PATH=/usr/local/Cellar/postgresql@9.6/9.6.7/:$PATH make install
  - env PATH=/usr/local/Cellar/postgresql/9.6.5/:$PATH make install
  - rm /usr/local/share/postgresql/extension/temporal_tables--*--*.sql
  - |
    tar -cJf postgresql-Darwin-x86_64.txz \
#    -C /usr/local/Cellar/postgresql@9.6/9.6.7 \
    -C /usr/local/Cellar/postgresql/9.6.5 \
    share/postgresql \
    lib/libicudata.57.dylib \
    lib/libicui18n.57.dylib \
    lib/libicuuc.57.dylib \
    lib/libxml2.2.dylib \
    lib/libssl.1.0.0.dylib \
    lib/libcrypto.1.0.0.dylib \
    lib/libuuid.1.1.dylib \
    lib/postgresql/*.so \
    bin/initdb \
    bin/pg_ctl \
    bin/pg_restore \
    bin/postgres
  - find /usr/local/Cellar/postgresql
  - otool -L /usr/local/bin/postgres
  - otool -L /usr/local/bin/initdb
before_deploy:
  - git config --local user.name "Benjamin Albrecht"
  - git config --local user.email "git@albrecht.io"
  - git tag $VERSION
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: b47gkaug9LuFa68rH8JmbdcRhuo5H5d3gnAgxGKMzoIDsN30BUsbiEmgFDoa3boBuOrknTlDsmqtMfvNQ/HsB6ez1QiPipOGUGIs+UC6f3jg7huvtVm4dDMZJrqL2p8drKQ+6HnBKDFaOLf6VyNyPqYzBCCHLmfhGpT450eBazqXmLyrC+cIFdq5nzfV8K0LekPVs8QhZTPpkn6kiJlD2k/WvUrlJ1UnchR5ZsgPd0JdHCb6yPd98t83wVtYeUsNJgpTuSfr14p0jGTDY7/y3xXYukO9GOnd9qGDKfkbS311mo8n+94cvF0NDPrmh/XiaUv8hDa+ocxYH42XGMJP1TKTTEakBY/wK1wgyZBsSMn3cmmlKiclTo60UHjXBQ4swELcrUtOXytqWP0rxbFy/MAu7XBSclcLfwhDx4fctr9tzHphWSxeeKtC3mySm5FiSgEThahKNiGai1VgtvWEAu+OXTVHZn9iaQ67LJbRclg5sbPAVff7CUkxstnkgNBeyb+/k9nVMGojXoBCzqUhUqYUrqO5cUoWhLHJCZpTqZJA+A4Rmet2xV9uxhM4xg6aUdrNh+ve03BtD9Ce9gic23MPks7vcg2h3Zh6iG4S0S46d5Idp1JgPM0+DzsT6qInLWJhEWpOdPiN2+LyVUGW1SuiUbVRSHMnWTkLNRR3NjE=
  file: dist/pgsql/postgresql-Darwin-x86_64.txz
  on:
    repo: benalbrecht/temporal_tables
